// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ReHeaterAPI.AI
{
    public class ModelInput
    {
        [ColumnName("Tzew"), LoadColumn(0)]
        public float Tzew { get; set; }


        [ColumnName("Tstart"), LoadColumn(1)]
        public float Tstart { get; set; }


        [ColumnName("Qg"), LoadColumn(2)]
        public float Qg { get; set; }


        [ColumnName("Area"), LoadColumn(3)]
        public float Area { get; set; }


        [ColumnName("iterations"), LoadColumn(4)]
        public float Iterations { get; set; }


        [ColumnName("Tend"), LoadColumn(5)]
        public float Tend { get; set; }


    }
}
